import routesConstants from "./routesConstants";
import {
  _404,
  Dashboard,
  Login,
  Insight_metrics,
  Insight_metrics_v2,
  Alert_subscription,
  Get_usage,
  Usuage,
  Profile,
  ChangePassword,
  Account,
  AddAccount,
  Opportunity,
  Subscription,
  NewSubscription,
  DeletedSubscription,
  ChangeLogSubscription,
  CompareSubscription,
  UniqueUserCount,
  ProductMaster,
  Product,
  AddUpdateProductMaster,
  Notifications,
  AddUpdateProduct,
  orderLoadingToHO,
  AddEditOrderLoadingHO,
  ManageTemplate,
  ManageTeams,
  Upload,
  UploadBulk,
  PaymentsOverdue,
  PaymentsOutstanding,
  InvoicePending,
  RenewalEmailSent,
  OrderLoadingHOListing,
  OrderLoadingDistributor,
  RAOrder,
  License_optization,
  ContactInformation,
  AddEditNewQuotaion,
  License_Optimisation_View,
  NewQuotaion,
  NewOpportunity,
  AddNewOpportunity,
  CampaignHistory,
  RunCampaign,
  SelectCampaignAudience,
  FinalCampaign,
  ExportedFile,
  DownloadHistory,
  UploadHistory,
  ComingSoon,
  RenewalDue,
  BackupOperation,
  PermissionProfile,
  Calendar,
  GenerateTicket,
} from "./routeImports";
import { Outlet } from "react-router-dom";
import { userType } from "@/constants";
import { moduleId } from "@/constants/ConstantConfig";

const routesConfig = {
  common: [{ path: routesConstants._404, component: _404 }],
  private: [
    {
      path: routesConstants.DASHBOARD,
      component: Outlet,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.Dashboard,
      children: [
        {
          index: true,
          component: Dashboard,
          roles: [
            userType.superadmin,
            userType.client,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.Dashboard,
        },
        {
          path: "payments_overdue",
          component: PaymentsOverdue,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.Dashboard,
        },
        {
          path: "payments_outstanding",
          component: PaymentsOutstanding,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.Dashboard,
        },
        {
          path: "invoice_pending",
          component: InvoicePending,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.Dashboard,
        },
      ],
    },
    {
      path: routesConstants.RENEW_DUE,
      component: RenewalDue,
      roles: [userType.client],
      moduleId: moduleId.Dashboard,
    },
    {
      path: routesConstants.INSIGHT_METRICS,
      component: Insight_metrics,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.InsightMetrics,
    },
    {
      path: routesConstants.INSIGHT_METRICS_V2,
      component: Insight_metrics_v2,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.InsightMetricsV2,
    },
    {
      path: routesConstants.ALERT_SUBSCRIPTION,
      component: Alert_subscription,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.RorAlert,
    },
    {
      path: routesConstants.GET_USAGE,
      component: Outlet,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.GetUsages,
      children: [
        {
          index: true,
          component: Get_usage,
          roles: [
            userType.superadmin,
            userType.client,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.GetUsages,
        },
        {
          path: "usage/:csn/:from_date/:to_date",
          component: Usuage,
          roles: [
            userType.superadmin,
            userType.client,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.GetUsages,
        },
        {
          path: "usage_user_count/:csn/:from_date/:to_date",
          component: UniqueUserCount,
          roles: [
            userType.superadmin,
            userType.client,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.GetUsages,
        },
      ],
    },
    {
      path: routesConstants?.LICENSE_OPTIMIZATION,
      component: Outlet,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.LicenseOptimization,
      children: [
        {
          index: true,
          component: License_optization,
          roles: [
            userType.superadmin,
            userType.client,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.LicenseOptimization,
        },
        {
          path: "view_license_optimization/:accountId/:branchId/:productId/:startDate/:endDate",
          component: License_Optimisation_View,
          roles: [
            userType.superadmin,
            userType.client,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.LicenseOptimization,
        },
      ],
    },
    {
      path: routesConstants.ACCOUNT,
      component: Account,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.Account,
    },
    {
      path: routesConstants.ADD_ACCOUNT,
      component: AddAccount,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.AddAccount,
    },
    {
      path: routesConstants.UPDATE_ACCOUNT + `/:id`,
      component: AddAccount,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.AddAccount,
    },
    {
      path: routesConstants.THIRD_PARTY_ACCOUNT,
      component: Account,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.ThirdPartyAccount,
    },
    {
      path: routesConstants.OPPORTUNITY,
      component: Opportunity,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.RenewalOpportunity,
    },
    {
      path: routesConstants.NEW_OPPORTUNITY,
      component: Outlet,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.NewOpportunity,
      children: [
        {
          index: true,
          component: NewOpportunity,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.NewOpportunity,
        },
        {
          path: "add_new_opportunity",
          component: AddNewOpportunity,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.NewOpportunity,
        },
        {
          path: ":opportunityId",
          component: AddNewOpportunity,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.NewOpportunity,
        },
      ],
    },
    {
      path: routesConstants.NEW_QUOTATION,
      component: Outlet,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.NewQuotation,
      children: [
        {
          index: true,
          component: NewQuotaion,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.NewQuotation,
        },
        {
          path: "add_new_quotation",
          component: AddEditNewQuotaion,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.NewQuotation,
        },
        {
          path: ":quotationId",
          component: AddEditNewQuotaion,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.NewQuotation,
        },
      ],
    },

    {
      path: routesConstants.SUBSCRIPTION,
      component: Subscription,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.Subscription,
    },
    {
      path: routesConstants.NEW_SUBSCRIPTION,
      component: NewSubscription,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.NewSubscription,
    },
    {
      path: routesConstants.DELETED_SUBSCRIPTION,
      component: DeletedSubscription,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.DeletedSubscription,
    },
    {
      path: routesConstants.CHANGED_LOG_SUBSCRIPTION,
      component: ChangeLogSubscription,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.ChangeLogComparison,
    },
    {
      path: routesConstants.SUBSCRIPTION_DATA_COMPARISON,
      component: CompareSubscription,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.SubscriptionDataComparison,
    },
    {
      path: routesConstants.ORDER_LOADING_PO,
      component: Outlet,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.OrderLoadingHO,
      children: [
        {
          index: true,
          component: orderLoadingToHO,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.OrderLoadingHO,
        },
        {
          path: "add_order_loading_po",
          component: AddEditOrderLoadingHO,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.OrderLoadingHO,
        },
        {
          path: "update_order_loading_po/:orderLoadingHoId",
          component: AddEditOrderLoadingHO,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.OrderLoadingHO,
        },
        {
          path: "order_loading_po_list",
          component: OrderLoadingHOListing,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.OrderLoadingHO,
        },
      ],
    },
    {
      path: routesConstants.ORDER_LOADING_DISTRIBUTOR,
      component: OrderLoadingDistributor,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.OrderLoadingDistributor,
    },
    {
      path: routesConstants.RA_ORDER,
      component: RAOrder,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.RAOrder,
    },
    {
      path: routesConstants.MANAGE_TEAM,
      component: ManageTeams,
      roles: [userType.superadmin],
      moduleId: moduleId.ManageTeam,
    },
    {
      path: routesConstants.MANAGE_TEMPLATE,
      component: ManageTemplate,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.ManageTemplate,
    },
    {
      path: routesConstants.DOWNLOAD_HISTORY,
      component: DownloadHistory,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.DownloadHistory,
    },
    {
      path: routesConstants.UPLOAD,
      component: Outlet,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.Upload,
      children: [
        {
          index: true,
          component: Upload,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.Upload,
        },
        {
          path: "upload_bulk",
          component: UploadBulk,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.Upload,
        },
      ],
    },
    {
      path: routesConstants.UPLOAD_HISTORY,
      component: UploadHistory,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.UploadHistory,
    },
    {
      path: routesConstants.EXPORTED_FILE,
      component: ExportedFile,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
    },
    {
      path: routesConstants.PRODUCT_MASTER,
      component: Outlet,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.ProductMaster,
      children: [
        {
          index: true,
          component: ProductMaster,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.ProductMaster,
        },
        {
          path: "add_product_master",
          component: AddUpdateProductMaster,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.ProductMaster,
        },
        {
          path: "update_product_master/:productMasterId",
          component: AddUpdateProductMaster,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.ProductMaster,
        },
      ],
    },
    {
      path: routesConstants.PRODUCT,
      component: Outlet,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.Product,
      children: [
        {
          index: true,
          component: Product,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.Product,
        },
        {
          path: "add_product",
          component: AddUpdateProduct,
          roles: [
            userType.superadmin,
            userType.bdManager,
            userType.primaryAdmin,
          ],
          moduleId: moduleId.Product,
        },
      ],
    },
    {
      path: routesConstants.RUN_CAMPAIGN,
      component: RunCampaign,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.RunCampaign,
    },
    {
      path: routesConstants?.CAMPAIGN_AUDIENCE,
      component: SelectCampaignAudience,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.RunCampaign,
    },
    {
      path: routesConstants?.FINAL_CAMPAIGN,
      component: FinalCampaign,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.RunCampaign,
    },
    {
      path: routesConstants.CAMPAIGN_HISTORY,
      component: CampaignHistory,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.CampaignHistory,
    },
    {
      path: routesConstants.CONTACT_INFORMATION,
      component: ContactInformation,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.ContactInformation,
    },
    {
      path: routesConstants.RENEW_HISTORY,
      component: RenewalEmailSent,
      roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
      moduleId: moduleId.RenewEmailHistory,
    },
    {
      path: routesConstants.LEARNING_LAB,
      component: ComingSoon,
      roles: [userType.client],
      moduleId: moduleId.LearningLab,
    },
    {
      path: routesConstants.PRODUCT_KNOWLEDGE,
      component: ComingSoon,
      roles: [userType.client],
      moduleId: moduleId.ProductKnowledge,
    },
    {
      path: routesConstants.TRAINING_SESSION,
      component: ComingSoon,
      roles: [userType.client],
      moduleId: moduleId.RequestTrainingSession,
    },
    // {
    //   path: routesConstants.PROFILE_FORM,
    //   component: Get_usage,
    //   roles: [userType.superadmin, userType.client],
    // },
    {
      path: routesConstants.GENERATE_TICKET,
      component: GenerateTicket,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.GenerateTicket,
    },
    {
      path: routesConstants.CALENDAR,
      component: Calendar,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.Calendar,
    },
    {
      path: routesConstants.FAQ,
      component: ComingSoon,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
      moduleId: moduleId.Faqs,
    },
    {
      path: routesConstants.PROFILE + `/:id`,
      component: Profile,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
    },
    {
      path: routesConstants?.CHANGE_PASSWORD,
      component: ChangePassword,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
    },
    {
      path: routesConstants?.NOTIFICATIONS,
      component: Notifications,
      roles: [
        userType.superadmin,
        userType.client,
        userType.bdManager,
        userType.primaryAdmin,
      ],
    },
    {
      path: routesConstants?.BACKUP_OPERATION,
      component: BackupOperation,
      roles: [userType.superadmin],
    },
    {
      path: routesConstants?.PERMISSION_PROFILE,
      component: PermissionProfile,
      roles: [userType.superadmin],
    },
  ],
  public: [{ path: routesConstants?.LOGIN, component: Login }],
};

export default routesConfig;
