const routesConstants = {
  DASHBOARD: "/dashboard",
  INSIGHT_METRICS: "/insight_metrics",
  INSIGHT_METRICS_V2: "/insight_metrics_v2",
  ALERT_SUBSCRIPTION: "/alert_subscription",
  GET_USAGE: "/get_usage",
  ACCOUNT: "/account",
  ADD_ACCOUNT: "/add_account",
  THIRD_PARTY_ACCOUNT: "/third_party_account",
  OPPORTUNITY: "/opportunity",
  QUOTATION: "/quotation",
  SUBSCRIPTION: "/subscription",
  NEW_SUBSCRIPTION: "/new_subscription",
  DELETED_SUBSCRIPTION: "/deleted_subscription",
  CHANGED_LOG_SUBSCRIPTION: "/change_log_subscription",
  SUBSCRIPTION_DATA_COMPARISON: "/campare_subscription",
  ORDER_LOADING_PO: "/order_loading_po",
  ORDER_LOADING_DISTRIBUTOR: "/order_loading_distributor",
  RA_ORDER: "/ra_order_subscription",
  EXPORTED_FILE: "/exported_file",
  PRODUCT_MASTER: "/product_master",
  PRODUCT: "/product",
  RUN_CAMPAIGN: "/select_audience",
  CAMPAIGN_HISTORY: "/campaign_history",
  CONTACT_INFORMATION: "/contact_information",
  RENEW_HISTORY: "/renew_history",
  PROFILE_FORM: "/form",
  CALENDAR: "/calendar",
  FAQ: "/faq",
  LOGIN: "/login",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change_password",
  UNAUTHORIZED: "/unauthorized",
  _404: "*",
};
export default routesConstants;
