import routesConstants from "@/routes/routesConstants";
import HomeOutlinedIcon from "@mui/icons-material/HomeOutlined";
import PeopleOutlinedIcon from "@mui/icons-material/PeopleOutlined";
import PersonOutlinedIcon from "@mui/icons-material/PersonOutlined";
import ContactsOutlinedIcon from "@mui/icons-material/ContactsOutlined";
import ReceiptOutlinedIcon from "@mui/icons-material/ReceiptOutlined";
import BorderAllIcon from "@mui/icons-material/BorderAll";
import Diversity3Icon from "@mui/icons-material/Diversity3";
import CalendarTodayOutlinedIcon from "@mui/icons-material/CalendarTodayOutlined";
import HelpOutlineOutlinedIcon from "@mui/icons-material/HelpOutlineOutlined";
import { userType } from ".";
export const moduleId = {
  Dashboard: 1,
  InsightMetrics: 2,
  InsightMetricsV2: 3,
  RorAlert: 4,
  GetUsages: 5,
  LicenseOptimization: 6,
  Account: 7,
  AddAccount: 8,
  ThirdPartyAccount: 9,
  RenewalOpportunity: 10,
  NewOpportunity: 11,
  NewQuotation: 12,
  Subscription: 13,
  NewSubscription: 14,
  DeletedSubscription: 15,
  ChangeLogComparison: 16,
  SubscriptionDataComparison: 17,
  OrderLoadingHO: 18,
  OrderLoadingDistributor: 19,
  RAOrder: 20,
  ManageTeam: 21,
  ManageTemplate: 22,
  Upload: 23,
  DownloadHistory: 24,
  UploadHistory: 25,
  ProductMaster: 26,
  Product: 27,
  RunCampaign: 28,
  CampaignHistory: 29,
  ContactInformation: 30,
  RenewEmailHistory: 31,
  GenerateTicket: 32,
  Calendar: 33,
  Faqs: 34,
  LearningLab: 35,
  ProductKnowledge: 36,
  RequestTrainingSession: 37,
};

export const navLinks = [
  {
    name: "Dashboard",
    href: routesConstants?.DASHBOARD,
    roles: [
      userType.superadmin,
      userType.client,
      userType.bdManager,
      userType.primaryAdmin,
    ],
    iconUrl: <HomeOutlinedIcon />,
    moduleId: moduleId.Dashboard,
  },
  {
    name: "Trisita Customer Success APIs",
    isLabel: true,
    roles: [
      userType.superadmin,
      userType.client,
      userType.bdManager,
      userType.primaryAdmin,
    ],
    modules: [
      moduleId.InsightMetrics,
      moduleId.InsightMetricsV2,
      moduleId.RorAlert,
      moduleId.GetUsages,
      moduleId.LicenseOptimization,
    ],
    item: [
      {
        itemName: "Insight Metrics",
        href: routesConstants?.INSIGHT_METRICS,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.InsightMetrics,
      },
      {
        itemName: "Insight Metrics V2",
        href: routesConstants?.INSIGHT_METRICS_V2,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.InsightMetricsV2,
      },
      {
        itemName: "ROR/LTC Alert",
        href: routesConstants?.ALERT_SUBSCRIPTION,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.RorAlert,
      },
      {
        itemName: "Get Usage",
        href: routesConstants?.GET_USAGE,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.GetUsages,
      },
      {
        itemName: "License Optimization",
        href: routesConstants?.LICENSE_OPTIMIZATION,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.LicenseOptimization,
      },
    ],
  },
  {
    name: "Trisita Sales API",
    isLabel: true,
    roles: [
      userType.superadmin,
      userType.client,
      userType.bdManager,
      userType.primaryAdmin,
    ],
    modules: [
      moduleId.Account,
      moduleId.AddAccount,
      moduleId.ThirdPartyAccount,
      moduleId.RenewalOpportunity,
      moduleId.NewOpportunity,
      moduleId.NewQuotation,
    ],
    item: [
      {
        itemName: "Account",
        href: routesConstants?.ACCOUNT,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.Account,
      },
      {
        itemName: "Add Account",
        href: routesConstants?.ADD_ACCOUNT,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.AddAccount,
      },
      {
        itemName: "Third Party Account",
        href: routesConstants?.THIRD_PARTY_ACCOUNT,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.ThirdPartyAccount,
      },
      {
        itemName: "Renewal Opportunity",
        href: routesConstants?.OPPORTUNITY,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.RenewalOpportunity,
      },
      {
        itemName: "New Opportunity",
        href: routesConstants?.NEW_OPPORTUNITY,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.NewOpportunity,
      },
      {
        itemName: "New Quotation",
        href: routesConstants?.NEW_QUOTATION,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.NewQuotation,
      },
    ],
  },
  {
    name: "Trisita Subscription API",
    isLabel: true,
    roles: [
      userType.superadmin,
      userType.client,
      userType.bdManager,
      userType.primaryAdmin,
    ],
    modules: [
      moduleId.Subscription,
      moduleId.NewSubscription,
      moduleId.DeletedSubscription,
      moduleId.ChangeLogComparison,
      moduleId.SubscriptionDataComparison,
    ],
    item: [
      {
        itemName: "Subscription",
        href: routesConstants?.SUBSCRIPTION,
        iconUrl: <ReceiptOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.Subscription,
      },
      {
        itemName: "New Subscription",
        href: routesConstants?.NEW_SUBSCRIPTION,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.NewSubscription,
      },
      {
        itemName: "Deleted Subscription",
        href: routesConstants?.DELETED_SUBSCRIPTION,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.DeletedSubscription,
      },
      {
        itemName: "Change Log Comparison",
        href: routesConstants?.CHANGED_LOG_SUBSCRIPTION,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.ChangeLogComparison,
      },
      {
        itemName: "Subscription Data Comparison",
        href: routesConstants?.SUBSCRIPTION_DATA_COMPARISON,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.SubscriptionDataComparison,
      },
    ],
  },
  {
    name: "Trisita Order Loading API",
    isLabel: true,
    roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
    modules: [
      moduleId.OrderLoadingHO,
      moduleId.OrderLoadingDistributor,
      moduleId.RAOrder,
    ],
    item: [
      {
        itemName: "Order Loading to HO",
        href: routesConstants?.ORDER_LOADING_PO,
        iconUrl: <BorderAllIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.OrderLoadingHO,
      },
      {
        itemName: "Order Loading to Distributor",
        href: routesConstants?.ORDER_LOADING_DISTRIBUTOR,
        iconUrl: <ReceiptOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.OrderLoadingDistributor,
      },
      {
        itemName: "RA Order",
        href: routesConstants?.RA_ORDER,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.RAOrder,
      },
    ],
  },
  {
    name: "Data",
    isLabel: true,
    roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
    modules: [
      moduleId.ManageTeam,
      moduleId.ManageTemplate,
      moduleId.Upload,
      moduleId.DownloadHistory,
      moduleId.UploadHistory,
      moduleId.ProductMaster,
      moduleId.Product,
      moduleId.RunCampaign,
      moduleId.CampaignHistory,
      moduleId.ContactInformation,
      moduleId.RenewEmailHistory,
    ],
    item: [
      {
        itemName: "Manage Team",
        href: routesConstants?.MANAGE_TEAM,
        iconUrl: <Diversity3Icon />,
        roles: [userType.superadmin],
        moduleId: moduleId.ManageTeam,
      },
      {
        itemName: "Manage Template",
        href: routesConstants?.MANAGE_TEMPLATE,
        iconUrl: <Diversity3Icon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.ManageTemplate,
      },
      {
        itemName: "Upload",
        href: routesConstants?.UPLOAD,
        iconUrl: <ReceiptOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.Upload,
      },
      {
        itemName: "Download History",
        href: routesConstants?.DOWNLOAD_HISTORY,
        iconUrl: <Diversity3Icon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.DownloadHistory,
      },
      {
        itemName: "Upload History",
        href: routesConstants?.UPLOAD_HISTORY,
        iconUrl: <Diversity3Icon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.UploadHistory,
      },
      // {
      //   itemName: "Exported File",
      //   href: routesConstants?.EXPORTED_FILE,
      //   iconUrl: <Diversity3Icon />,
      // },
      {
        itemName: "Product Master",
        href: routesConstants?.PRODUCT_MASTER,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.ProductMaster,
      },
      {
        itemName: "Product",
        href: routesConstants?.PRODUCT,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.Product,
      },
      {
        itemName: "Run Campaign",
        href: routesConstants?.RUN_CAMPAIGN,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.RunCampaign,
      },
      {
        itemName: "Campaign History",
        href: routesConstants?.CAMPAIGN_HISTORY,
        iconUrl: <PeopleOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.CampaignHistory,
      },
      {
        itemName: "Contacts Information",
        href: routesConstants?.CONTACT_INFORMATION,
        iconUrl: <ContactsOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.ContactInformation,
      },
      {
        itemName: "Renew Email History",
        href: routesConstants?.RENEW_HISTORY,
        iconUrl: <ReceiptOutlinedIcon />,
        roles: [userType.superadmin, userType.bdManager, userType.primaryAdmin],
        moduleId: moduleId.RenewEmailHistory,
      },
    ],
  },
  {
    name: "Knowledge Portal",
    isLabel: true,
    roles: [userType.client],
    modules: [
      moduleId.LearningLab,
      moduleId.ProductKnowledge,
      moduleId.RequestTrainingSession,
    ],
    item: [
      {
        itemName: "Learning Lab",
        href: routesConstants?.LEARNING_LAB,
        iconUrl: <PersonOutlinedIcon />,
        roles: [userType.client],
        moduleId: moduleId.LearningLab,
      },
      {
        itemName: "Product Knowledge",
        href: routesConstants?.PRODUCT_KNOWLEDGE,
        iconUrl: <PersonOutlinedIcon />,
        roles: [userType.client],
        moduleId: moduleId.ProductKnowledge,
      },
      {
        itemName: "Request Training Session",
        href: routesConstants?.TRAINING_SESSION,
        iconUrl: <CalendarTodayOutlinedIcon />,
        roles: [userType.client],
        moduleId: moduleId.RequestTrainingSession,
      },
    ],
  },
  {
    name: "Pages",
    isLabel: true,
    roles: [
      userType.superadmin,
      userType.client,
      userType.bdManager,
      userType.primaryAdmin,
    ],
    modules: [moduleId.GenerateTicket, moduleId.Calendar, moduleId.Faqs],
    item: [
      // {
      //   itemName: "Profile Form",
      //   href: routesConstants?.PROFILE_FORM,
      //   iconUrl: <PersonOutlinedIcon />,
      //   roles: [userType.superadmin, userType.client],
      // },
      {
        itemName: "Generate Ticket",
        href: routesConstants?.GENERATE_TICKET,
        iconUrl: <PersonOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.GenerateTicket,
      },
      {
        itemName: "Calendar",
        href: routesConstants?.CALENDAR,
        iconUrl: <CalendarTodayOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.Calendar,
      },
      {
        itemName: "FAQ Page",
        href: routesConstants?.FAQ,
        iconUrl: <HelpOutlineOutlinedIcon />,
        roles: [
          userType.superadmin,
          userType.client,
          userType.bdManager,
          userType.primaryAdmin,
        ],
        moduleId: moduleId.Faqs,
      },
    ],
  },

  {
    name: "Super Admin Console",
    isLabel: true,
    roles: [userType.superadmin],
    modules: [moduleId.Dashboard],
    item: [
      {
        itemName: "Backup Operation",
        href: routesConstants?.BACKUP_OPERATION,
        iconUrl: <PersonOutlinedIcon />,
        roles: [userType.superadmin],
        moduleId: moduleId.Dashboard,
      },
      {
        itemName: "Profile Permission",
        href: routesConstants?.PERMISSION_PROFILE,
        iconUrl: <PersonOutlinedIcon />,
        roles: [userType.superadmin],
        moduleId: moduleId.Dashboard,
      },
    ],
  },
];
