export const options = [
  {
    label: "Mumbai",
    value: 1,
  },
  {
    label: "Kolkata",
    value: 2,
  },
  {
    label: "Delhi",
    value: 3,
  },
];
export const statusOption = [
  { value: "All Status", label: "All Status" },
  { value: "Active", label: "Active" },
  { value: "Expired", label: "Expired" },
];
export const accountOption = [
  {
    label: "1 Architectural Consultants",
    csn: 5501593303,
    id: 6874,
  },
  {
    label: "2M RESEARCH PRIVATE Ltd",
    csn: 5501281536,
    id: 5858,
  },
  {
    label: "2M RESEARCH PVT. Ltd",
    csn: 5502185195,
    id: 6850,
  },
  {
    label: "2 Tettra School",
    csn: 5106985515,
    id: 5477,
  },
  {
    label: "3 Guys",
    csn: 5106740834,
    id: 6115,
  },
  {
    label: "4TH DIMENSION",
    csn: 5104091953,
    id: 4274,
  },
  {
    label: "99 Watts Energy Solutions Pvt. Ltd",
    csn: 5153000319,
    id: 4084,
  },
  {
    label: "A1 Jumbo Xerox",
    csn: 5114508998,
    id: 6255,
  },
  {
    label: "A2G CIVIL ENGINEERING SERVICES PVT. LTD",
    csn: 5122596593,
    id: 6163,
  },
  {
    label: "A4 Creation Pty Ltd",
    csn: 5100805535,
    id: 4013,
  },
  {
    label: "AABSYS INFORMATION TECHNOLOGY PVT",
    csn: 5138960616,
    id: 3021,
  },
  {
    label: "AABSYS INFORMATION TECHNOLOGY PVT. Ltd",
    csn: 5151235656,
    id: 6181,
  },
  {
    label: "AABSYSINFORMATIONTECHNOLOGYPVTLTD",
    csn: 5109908502,
    id: 5361,
  },
  {
    label: "AABSYS INFO TECH PVT. Ltd",
    csn: 5123161029,
    id: 5470,
  },
  {
    label: "AADHYA ANIMATICS PVT Ltd",
    csn: 5502315575,
    id: 6975,
  },
  {
    label: "AADITYA INNOVATIONS PVT. Ltd",
    csn: 5501755245,
    id: 6337,
  },
  {
    label: "AAKAAR",
    csn: 5125174500,
    id: 3009,
  },
  {
    label: "AAKAAR ARCHITECTS",
    csn: 5501676962,
    id: 6171,
  },
  {
    label: "AAKAR",
    csn: 5108569378,
    id: 5125,
  },
  {
    label: "Aakar Architects",
    csn: 5156470531,
    id: 6766,
  },
];
export const withoutProparated = {
  options: {
    chart: {
      height: 350,
      type: "bar",
    },
    xaxis: {
      labels: {},
      categories: [
        "MAYA",
        "AECCOL",
        "NAVSIM",
        "3DSMAX",
        "ACDLT",
        "PDCOLL",
        "VLTM",
        "BM36DP",
        "RVT",
        "RVTLTS",
        "MECOLL",
        "ACDIST",
        "COLLRP",
        "CIV3D",
        "PREMSUB",
        "ADSTPR",
        "FSN",
        "SCFDM",
        "F360PMU",
        "BLD5K",
        "F360PS",
        "F360PMS",
        "CAMDCT",
        "SPCMKR",
        "F36FCS",
        "ACDLTM",
        "INVPROSA",
        "BIMCOLL",
        "BLD550",
        "F360",
        "F360PD",
        "NAVMAN",
        "BLDUNLT",
        "A250",
        "F36MEIA",
        "PCOFFI",
        "DOCS",
        "CADMEP",
        "IWICMU",
        "INFDU",
        "INFWP",
        "QNTFY",
        "IWWSPRO",
        "F36FC",
      ],
    },
    yaxis: {
      title: {
        text: "Count",
      },
    },
    colors: ["#007BFF", "#28A745", "#FFC107"],
    plotOptions: {
      bar: {
        borderRadius: 0,
        columnWidth: "80%",
      },
    },
  },
  series: [
    {
      name: "Seats Purchased",
      data: [
        124, 2061, 299, 114, 2106, 823, 235, 650, 48, 15, 73, 1360, 580, 187,
        47, 11, 36, 1, 5, 4, 22, 34, 1, 1, 1, 3, 42, 12, 6, 2, 1, 4, 10004, 3,
        1, 1, 17, 2, 3, 2, 2, 3, 2, 1,
      ],
    },
    {
      name: "User Assigned",
      data: [
        95, 1944, 192, 102, 1898, 771, 212, 533, 43, 15, 72, 1236, 507, 178, 0,
        11, 33, 1, 4, 4, 20, 33, 1, 1, 1, 3, 42, 11, 6, 2, 1, 3, 7, 3, 1, 0, 16,
        0, 3, 2, 0, 2, 2, 1,
      ],
    },
    {
      name: "Seats In Use",
      data: [
        71, 1622, 150, 69, 1249, 551, 125, 317, 26, 10, 62, 924, 368, 142, 0, 8,
        26, 1, 3, 3, 14, 28, 1, 0, 0, 0, 32, 6, 4, 1, 1, 2, 3, 3, 0, 0, 4, 0, 1,
        0, 0, 0, 0, 1,
      ],
    },
  ],
};
export const withProparated = {
  options: {
    chart: {
      height: 350,
      type: "bar",
    },
    xaxis: {
      labels: {
        rotate: -45,
      },
      categories: [
        "MAYA",
        "AECCOL",
        "NAVSIM",
        "3DSMAX",
        "ACDLT",
        "PDCOLL",
        "VLTM",
        "RVT",
        "RVTLTS",
        "MECOLL",
        "ACDIST",
        "COLLRP",
        "CIV3D",
        "ADSTPR",
        "INVPROSA",
        "BLD550",
      ],
    },
    yaxis: {
      title: {
        text: "Count",
      },
    },
    colors: ["#007BFF", "#28A745", "#FFC107"],
    plotOptions: {
      bar: {
        borderRadius: 0,
        columnWidth: "80%",
      },
    },
  },
  series: [
    {
      name: "Seats Purchased",
      data: [
        9, 1612, 33, 69, 1532, 1064, 113, 37, 25, 18, 590, 521, 96, 13, 22, 8,
      ],
    },
    {
      name: "User Assigned ProRated",
      data: [
        "9.00",
        "1545.37",
        "33.00",
        "68.00",
        "1487.93",
        "981.31",
        "85.84",
        "35.01",
        "22.99",
        "14.01",
        "569.31",
        "500.62",
        "96.00",
        "13.00",
        "22.00",
        "8.00",
      ],
    },
    {
      name: "Seats In Use ProRated",
      data: [
        "9.00",
        "1366.05",
        "33.00",
        "54.01",
        "1190.00",
        "837.63",
        "43.07",
        "14.69",
        "10.03",
        "12.07",
        "414.92",
        "350.24",
        "71.05",
        "12.00",
        "22.00",
        "8.00",
      ],
    },
  ],
};
export const risk = {
  options: {
    chart: {
      type: "bar",
      height: 350,
      width: "100%",
      events: {},
    },
    xaxis: {
      categories: ["Green", "Yellow", "Red", "Unknown"],
    },
    yaxis: {
      title: {
        text: "",
      },
    },
    dataLabels: {
      position: "top",
    },
  },
  series: [
    {
      name: "contracts",
      data: [1870, 339, 667, 0],
    },
  ],
};
export const processedData = [
  {
    id: 396234,
    Account: "ADNET INFOSYSTEMS I PVT. Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Expired",
    bd_person_name: ["Rahul Chheda"],
    renewal_person_name: ["Rahul Chheda"],
    subs_end_date: null,
    partnerCSN: 5117963549,
    seatsPurchased: "14",
    contractNumber: 110004988552,
    customerCSN: 5123397612,
    ownerType: "ACCOUNT",
    productLineCode: "MAYA",
    seatsInUse: "0",
    usersAssigned: "0",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "0%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "AGCDRMYBR7KL",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Rahul Chheda",
    renewal_person: "Rahul Chheda",
  },
  {
    id: 396989,
    Account: "RA - Tech Engineering LLP",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-02-04",
    partnerCSN: 5117963549,
    seatsPurchased: "1",
    contractNumber: 110004664487,
    customerCSN: 5155322439,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "16101405",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 397121,
    Account: "Tata Consulting Engineers Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-03-10",
    partnerCSN: 5117963549,
    seatsPurchased: "1",
    contractNumber: 110004694293,
    customerCSN: 5109031808,
    ownerType: "ACCOUNT",
    productLineCode: "NAVSIM",
    seatsInUse: "0",
    usersAssigned: "1",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "17991586",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 396809,
    Account: "GETAFIXX (I)",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Rahul Chheda"],
    renewal_person_name: ["Rahul Chheda"],
    subs_end_date: "2025-03-13",
    partnerCSN: 5117963549,
    seatsPurchased: "4",
    contractNumber: 422100973480,
    customerCSN: 5103875761,
    ownerType: "ACCOUNT",
    productLineCode: "3DSMAX",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "8992473",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Rahul Chheda",
    renewal_person: "Rahul Chheda",
  },
  {
    id: 396902,
    Account: "RA-TECH ENGINEERING LLP",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-03-25",
    partnerCSN: 5117963549,
    seatsPurchased: "2",
    contractNumber: 110003948103,
    customerCSN: 5125198640,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "16101405",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 397029,
    Account: "INFOSYS TECHNOLOGIES Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-03-26",
    partnerCSN: 5117963549,
    seatsPurchased: "2",
    contractNumber: 110003501779,
    customerCSN: 5103720917,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: "2",
    usersAssigned: "2",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "15893555",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396593,
    Account: "DESIGN DIVISION",
    AccountStatus: "Active",
    branch: null,
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-03-27",
    partnerCSN: 5102086717,
    seatsPurchased: "1",
    contractNumber: 110001211438,
    customerCSN: 5126194564,
    ownerType: "ACCOUNT",
    productLineCode: "ACDLT",
    seatsInUse: "1",
    usersAssigned: "1",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "7615477",
    resellerCSN: 5102086717,
    resellerName: "TRISITA ENGINEERING LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396906,
    Account: "BLUE STAR Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-03-31",
    partnerCSN: 5117963549,
    seatsPurchased: "38",
    contractNumber: 110003518165,
    customerCSN: 5102909369,
    ownerType: "ACCOUNT",
    productLineCode: "PDCOLL",
    seatsInUse: "25",
    usersAssigned: "38",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "66%",
    usageRate: "66%",
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "15172907",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 396752,
    Account: "OBEROI REALTY Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-03-31",
    partnerCSN: 5117963549,
    seatsPurchased: "58",
    contractNumber: 110004336408,
    customerCSN: 5101174854,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: "58",
    usersAssigned: "58",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "29565821",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396919,
    Account: "BLUE STAR Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-03-31",
    partnerCSN: 5117963549,
    seatsPurchased: "124",
    contractNumber: 110003518165,
    customerCSN: 5102909369,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "96%",
    usageRate: "96%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "15172907",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 396750,
    Account: "OBEROI REALTY Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-03-31",
    partnerCSN: 5117963549,
    seatsPurchased: "12",
    contractNumber: 110002599853,
    customerCSN: 5101174854,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: "8",
    usersAssigned: "10",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "83%",
    utilisationRate: "67%",
    usageRate: "80%",
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "9105067",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396694,
    Account: "L&T Special Steels and Heavy Forgings Pvt Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-03-31",
    partnerCSN: 5117963549,
    seatsPurchased: "4",
    contractNumber: 110004335076,
    customerCSN: 5152689939,
    ownerType: "ACCOUNT",
    productLineCode: "PDCOLL",
    seatsInUse: "4",
    usersAssigned: "4",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "17428204",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396862,
    Account: "CASA PARADOX PVT. Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-04-01",
    partnerCSN: 5117963549,
    seatsPurchased: "1",
    contractNumber: 110004715183,
    customerCSN: 5501694486,
    ownerType: "ACCOUNT",
    productLineCode: "3DSMAX",
    seatsInUse: "1",
    usersAssigned: "1",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "8329945",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 397052,
    Account: "RA-TECH ENGINEERING LLP",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-04-01",
    partnerCSN: 5117963549,
    seatsPurchased: "3",
    contractNumber: 110003514425,
    customerCSN: 5151104808,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: "0",
    usersAssigned: "3",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "16101405",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 397028,
    Account: "INFOSYS TECHNOLOGIES Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-04-02",
    partnerCSN: 5117963549,
    seatsPurchased: "8",
    contractNumber: 110003501780,
    customerCSN: 5103720917,
    ownerType: "ACCOUNT",
    productLineCode: "NAVSIM",
    seatsInUse: "2",
    usersAssigned: "8",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "25%",
    usageRate: "25%",
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "15893555",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 397025,
    Account: "TICS ENGINEERING LLP",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-04-03",
    partnerCSN: 5117963549,
    seatsPurchased: "2",
    contractNumber: 110004341282,
    customerCSN: 5501295711,
    ownerType: "ACCOUNT",
    productLineCode: "PDCOLL",
    seatsInUse: "0",
    usersAssigned: "2",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "9655828",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 397024,
    Account: "TICS ENGINEERING LLP",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-04-03",
    partnerCSN: 5117963549,
    seatsPurchased: "2",
    contractNumber: 110004341282,
    customerCSN: 5501295711,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: "0",
    usersAssigned: "2",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "9655828",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396899,
    Account: "RA-TECH ENGINEERING LLP",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-04-09",
    partnerCSN: 5117963549,
    seatsPurchased: "2",
    contractNumber: 110004722394,
    customerCSN: 5125198640,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "16101405",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 396900,
    Account: "RA-TECH ENGINEERING LLP",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-04-09",
    partnerCSN: 5117963549,
    seatsPurchased: "2",
    contractNumber: 110004722386,
    customerCSN: 5125198640,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "16101405",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 396743,
    Account: "BLUE STAR Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-04-11",
    partnerCSN: 5117963549,
    seatsPurchased: "1",
    contractNumber: 110004349089,
    customerCSN: 5501008098,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: "0",
    usersAssigned: "1",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "15172907",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 396935,
    Account: "SPARROWS OFFSHORE SERVICES INDIA PV",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-04-13",
    partnerCSN: 5117963549,
    seatsPurchased: "2",
    contractNumber: 110004351616,
    customerCSN: 5146021294,
    ownerType: "ACCOUNT",
    productLineCode: "VLTM",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "56%",
    usageRate: "56%",
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "8369521",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396939,
    Account: "SPARROWS OFFSHORE SERVICES INDIA PV",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-04-13",
    partnerCSN: 5117963549,
    seatsPurchased: "1",
    contractNumber: 110004351616,
    customerCSN: 5146021294,
    ownerType: "ACCOUNT",
    productLineCode: "PDCOLL",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "8369521",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396933,
    Account: "SPARROWS OFFSHORE SERVICES INDIA PV",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-04-13",
    partnerCSN: 5117963549,
    seatsPurchased: "1",
    contractNumber: 110004351616,
    customerCSN: 5146021294,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: "1",
    usersAssigned: "1",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "8369521",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396744,
    Account: "Raheja Universal Pvt. Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    subs_end_date: "2025-04-15",
    partnerCSN: 5117963549,
    seatsPurchased: "25",
    contractNumber: 110004724664,
    customerCSN: 5138391971,
    ownerType: "ACCOUNT",
    productLineCode: "BM36DP",
    seatsInUse: "10",
    usersAssigned: "20",
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "80%",
    utilisationRate: "40%",
    usageRate: "50%",
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "32980570",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 396988,
    Account: "RA - Tech Engineering LLP",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    subs_end_date: "2025-04-19",
    partnerCSN: 5117963549,
    seatsPurchased: "3",
    contractNumber: 110004358856,
    customerCSN: 5155322439,
    ownerType: "ACCOUNT",
    productLineCode: "AECCOL",
    seatsInUse: null,
    usersAssigned: null,
    seatsInUseProRated: null,
    usersAssignedProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "16101405",
    resellerCSN: 5117963549,
    resellerName: "Trisita Engineering LLP",
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
];
export const columns = [
  {
    field: "id",
    headerName: "Serial No.",
    width: 120,
  },
  {
    field: "contractNumber",
    headerName: "Contract#",
    width: 150,
  },
  {
    field: "customerCSN",
    headerName: "customerCSN",
    width: 150,
  },
  {
    field: "bd_person",
    headerName: "BD Person Name",
    width: 200,
  },
  {
    field: "renewal_person",
    headerName: "Renewal Person Name",
    width: 200,
  },
  {
    field: "Account",
    headerName: "Account",
    width: 200,
  },
  {
    field: "AccountStatus",
    headerName: "Autodesk Account Status",
    width: 120,
  },
  {
    field: "contract_status",
    headerName: "Trisita Account Status",
    width: 120,
  },
  {
    field: "subs_end_date",
    headerName: "Subs End Date",
    width: 120,
  },
  {
    field: "branch",
    headerName: "Branch",
    width: 100,
  },
  {
    field: "productLineCode",
    headerName: "productLineCode",
    width: 200,
  },
  {
    field: "seatsPurchased",
    headerName: "seatsPurchased",
    width: 200,
  },
  {
    field: "usersAssigned",
    headerName: "usersAssigned",
    width: 200,
  },
  {
    field: "seatsInUse",
    headerName: "seatsInUse",
    width: 200,
  },
  {
    field: "assignmentRate",
    headerName: "assignmentRate",
    width: 200,
  },
  {
    field: "utilisationRate",
    headerName: "utilisationRate",
    width: 200,
  },
  {
    field: "usageRate",
    headerName: "usageRate",
    width: 200,
  },
  {
    field: "riskCategory",
    headerName: "riskCategory",
    width: 200,
  },
  {
    field: "engagementCategory",
    headerName: "engagementCategory",
    width: 200,
  },
  {
    field: "tenantId",
    headerName: "tenantId",
    width: 200,
  },
  
];
