export const processedData = [
  {
    id: 6077,
    account_id: "3772",
    subscriptionReferenceNumber: "574-78840831",
    account_name: "ANGELICA DEVELOPERS Ltd",
    account_csn: "5501729882",
    branch: "Delhi",
    startDate: "2024-04-25",
    endDate: "2025-04-24",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "deepak.sharma@bhartiland.com",
    seats: 5,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-04-25",
    contract_start_date: "2024-04-25",
    contract_end_date: "2025-04-24",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-04-25",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6076,
    account_id: "3772",
    subscriptionReferenceNumber: "574-78840732",
    account_name: "ANGELICA DEVELOPERS Ltd",
    account_csn: "5501729882",
    branch: "Delhi",
    startDate: "2024-04-25",
    endDate: "2025-04-24",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "deepak.sharma@bhartiland.com",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-04-25",
    contract_start_date: "2024-04-25",
    contract_end_date: "2025-04-24",
    productLine: "AutoCAD - including specialized toolsets",
    productLineCode: "ACDIST",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-04-25",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6075,
    account_id: "4571",
    subscriptionReferenceNumber: "574-79554473",
    account_name: "MIDREX TECHNOLOGIES",
    account_csn: "5501736455",
    branch: "Delhi",
    startDate: "2024-04-30",
    endDate: "2025-04-29",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "pkesharwani@midrex.in",
    seats: 3,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-04-30",
    contract_start_date: "2024-04-30",
    contract_end_date: "2025-04-29",
    productLine: "Product Design & Manufacturing Collection",
    productLineCode: "PDCOLL",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-04-22",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6074,
    account_id: "3965",
    subscriptionReferenceNumber: "777-13162616",
    account_name: "Pwd, Government of West Bengal",
    account_csn: "5154656559",
    branch: "Kolkata",
    startDate: "2022-07-22",
    endDate: "2025-07-21",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "bicsewb@gmail.com",
    seats: 7,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2022-07-22",
    contract_start_date: "2022-07-26",
    contract_end_date: "2025-07-21",
    productLine: "AutoCAD - including specialized toolsets",
    productLineCode: "ACDIST",
    retention_health_riskBand: "High",
    account_group: "Emerging Strategic Account",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-04-18",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6073,
    account_id: "3965",
    subscriptionReferenceNumber: "573-20575532",
    account_name: "Pwd, Government of West Bengal",
    account_csn: "5154656559",
    branch: "Kolkata",
    startDate: "2022-07-22",
    endDate: "2025-07-21",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "sapwdsouth@gmail.com",
    seats: 7,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2022-07-22",
    contract_start_date: "2022-07-22",
    contract_end_date: "2025-07-21",
    productLine: "AutoCAD - including specialized toolsets",
    productLineCode: "ACDIST",
    retention_health_riskBand: "High",
    account_group: "Emerging Strategic Account",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-04-18",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6072,
    account_id: "6632",
    subscriptionReferenceNumber: "575-07976265",
    account_name: "Larsen & Toubro Ltd Construction",
    account_csn: "5111760621",
    branch: "Mumbai",
    startDate: "2024-10-30",
    endDate: "2025-03-31",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "sramesh@lntecc.com",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-10-30",
    contract_start_date: "2024-11-06",
    contract_end_date: "2025-03-31",
    productLine: "Fusion",
    productLineCode: "FSN",
    retention_health_riskBand: null,
    account_group: "Emerging Strategic Account",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-04-10",
    programType: null,
    change_alert: "LTC",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6071,
    account_id: "6487",
    subscriptionReferenceNumber: "575-00179643",
    account_name: "Total Environment Building Systems Ltd",
    account_csn: "5500811082",
    branch: "Mumbai",
    startDate: "2024-08-22",
    endDate: "2025-03-27",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "premkumar.nallasamy@total-environment.com",
    seats: 13,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-08-22",
    contract_start_date: "2024-08-22",
    contract_end_date: "2026-03-23",
    productLine: "Architecture Engineering & Construction Collection",
    productLineCode: "AECCOL",
    retention_health_riskBand: "High",
    account_group: "Emerging Strategic Account",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-04-08T01:59:02.489727+05:30",
    programType: null,
    change_alert: "LTC",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6070,
    account_id: "6487",
    subscriptionReferenceNumber: "575-00179544",
    account_name: "Total Environment Building Systems Ltd",
    account_csn: "5500811082",
    branch: "Mumbai",
    startDate: "2024-08-22",
    endDate: "2025-03-27",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "premkumar.nallasamy@total-environment.com",
    seats: 4,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-08-22",
    contract_start_date: "2024-08-22",
    contract_end_date: "2026-03-23",
    productLine: "Revit",
    productLineCode: "RVT",
    retention_health_riskBand: "High",
    account_group: "Emerging Strategic Account",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-04-08T01:59:01.445394+05:30",
    programType: null,
    change_alert: "LTC",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6069,
    account_id: "5743",
    subscriptionReferenceNumber: "574-79138165",
    account_name: "Shyam Steel Industries Ltd",
    account_csn: "5154083179",
    branch: "Kolkata",
    startDate: "2024-04-27",
    endDate: "2025-04-26",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "sysadmin@shyamsteel.com",
    seats: 2,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-04-27",
    contract_start_date: "2024-04-27",
    contract_end_date: "2025-04-26",
    productLine: "AutoCAD - including specialized toolsets",
    productLineCode: "ACDIST",
    retention_health_riskBand: "Very High",
    account_group: "Emerging Strategic Account",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-04-08T01:59:00.429887+05:30",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6068,
    account_id: "2991",
    subscriptionReferenceNumber: "571-63590336",
    account_name: "UNITED ENGINEERS AND CONSULTANTS",
    account_csn: "5151110503",
    branch: "Kolkata",
    startDate: "2021-04-07",
    endDate: "2025-04-06",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "mrinmay@uecl.co.in",
    seats: 2,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-04-08",
    contract_start_date: "2021-04-07",
    contract_end_date: "2025-04-06",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-04-06T01:59:00.331734+05:30",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6067,
    account_id: "4424",
    subscriptionReferenceNumber: "574-67790650",
    account_name: "EKLAVYA HSG DKY JV",
    account_csn: "5501692708",
    branch: "Delhi",
    startDate: "2024-04-01",
    endDate: "2025-03-31",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "designdc04@yfcprojects.com",
    seats: 2,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-04-01",
    contract_start_date: "2024-04-01",
    contract_end_date: "2025-03-31",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-04-04T01:59:00.259893+05:30",
    programType: null,
    change_alert: "LTC",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6066,
    account_id: "5664",
    subscriptionReferenceNumber: "566-19668873",
    account_name: "Geeta Ganesh Promoters Ltd",
    account_csn: "5142196673",
    branch: "Kolkata",
    startDate: "2019-06-13",
    endDate: "2025-04-03",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "it@prasadgroup.co.in",
    seats: 2,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2022-03-27",
    contract_start_date: "2019-04-04",
    contract_end_date: "2025-04-03",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-03-30T01:59:00.337641+05:30",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6065,
    account_id: "3209",
    subscriptionReferenceNumber: "569-09450435",
    account_name: "PIONEER CONSULTANCY SERVICES",
    account_csn: "5142513742",
    branch: "Kolkata",
    startDate: "2020-04-27",
    endDate: "2025-04-26",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "subhasishdey1365@gmail.com",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-02-23",
    contract_start_date: "2020-04-27",
    contract_end_date: "2025-04-26",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-03-14T01:59:01.180610+05:30",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6064,
    account_id: "3209",
    subscriptionReferenceNumber: "566-16715818",
    account_name: "PIONEER CONSULTANCY SERVICES",
    account_csn: "5142513742",
    branch: "Kolkata",
    startDate: "2019-06-08",
    endDate: "2025-03-29",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "subhasishdey1365@gmail.com",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-02-23",
    contract_start_date: "2019-03-30",
    contract_end_date: "2025-03-29",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-03-14T01:59:00.312847+05:30",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6063,
    account_id: "4485",
    subscriptionReferenceNumber: "572-91521953",
    account_name: "EROS GROUP - AJAY ENTERPRISES PVT. Ltd",
    account_csn: "5137935395",
    branch: "Delhi",
    startDate: "2022-03-03",
    endDate: "2025-03-02",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "it@eros-group.com",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-02-28",
    contract_start_date: "2022-03-03",
    contract_end_date: "2025-03-02",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-03-11T01:59:00.233434+05:30",
    programType: null,
    change_alert: "LTC",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6062,
    account_id: "4738",
    subscriptionReferenceNumber: "571-99924556",
    account_name: "Strabag International GmbH",
    account_csn: "5151186292",
    branch: "Delhi",
    startDate: "2021-06-04",
    endDate: "2025-06-03",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "sysadmin@efkonindia.com",
    seats: 3,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-05-30",
    contract_start_date: "2021-06-04",
    contract_end_date: "2025-06-03",
    productLine: "Architecture Engineering & Construction Collection",
    productLineCode: "AECCOL",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-03-05T01:59:00.335007+05:30",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6061,
    account_id: "4968",
    subscriptionReferenceNumber: "568-40800565",
    account_name: "Narayan Sil Suvra",
    account_csn: "5123707634",
    branch: "Kolkata",
    startDate: "2020-03-02",
    endDate: "2025-03-01",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "silsuvra@yahoo.co.in",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-02-06",
    contract_start_date: "2020-03-02",
    contract_end_date: "2025-03-01",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    created_date: "2025-03-04T01:59:00.291408+05:30",
    programType: null,
    change_alert: "LTC",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6060,
    account_id: "4907",
    subscriptionReferenceNumber: "573-31165259",
    account_name: "UDYOGI PLASTICS PVT. Ltd",
    account_csn: "5114367639",
    branch: "Kolkata",
    startDate: "2022-09-18",
    endDate: "2025-07-26",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "it@udyogi.net",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-07-26",
    contract_start_date: "2022-07-27",
    contract_end_date: "2025-07-26",
    productLine: "Product Design & Manufacturing Collection",
    productLineCode: "PDCOLL",
    retention_health_riskBand: null,
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-02-13T01:59:04.975097+05:30",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6059,
    account_id: "4907",
    subscriptionReferenceNumber: "573-21867216",
    account_name: "UDYOGI PLASTICS PVT. Ltd",
    account_csn: "5114367639",
    branch: "Kolkata",
    startDate: "2022-07-27",
    endDate: "2025-07-26",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "it@udyogi.net",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-07-26",
    contract_start_date: "2022-07-27",
    contract_end_date: "2025-07-26",
    productLine: "Fusion 360 - Simulation Extension",
    productLineCode: "F360SE",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-02-13",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6058,
    account_id: "4907",
    subscriptionReferenceNumber: "573-53834951",
    account_name: "UDYOGI PLASTICS PVT. Ltd",
    account_csn: "5114367639",
    branch: "Kolkata",
    startDate: "2023-01-17",
    endDate: "2025-07-26",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "it@udyogi.net",
    seats: 2,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-07-26",
    contract_start_date: "2022-07-27",
    contract_end_date: "2025-07-26",
    productLine: "Product Design & Manufacturing Collection",
    productLineCode: "PDCOLL",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-02-13",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 6057,
    account_id: "4907",
    subscriptionReferenceNumber: "573-21867117",
    account_name: "UDYOGI PLASTICS PVT. Ltd",
    account_csn: "5114367639",
    branch: "Kolkata",
    startDate: "2022-07-27",
    endDate: "2025-07-26",
    subscriptionType: "Renewable Subscription",
    groupName: null,
    contract_manager_email: "it@udyogi.net",
    seats: 1,
    subscriptionStatus: "Active",
    lastPurchaseDate: "2024-07-26",
    contract_start_date: "2022-07-27",
    contract_end_date: "2025-07-26",
    productLine: "Product Design & Manufacturing Collection",
    productLineCode: "PDCOLL",
    retention_health_riskBand: "High",
    account_group: "Territory",
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Active",
    created_date: "2025-02-13",
    programType: null,
    change_alert: "ROR",
    bd_person: "",
    renewal_person: "",
  },
];

export const columns = [
  {
    field: "subscriptionReferenceNumber",
    headerName: "subscription",
    width: 150,
  },
  {
    field: "account_name",
    headerName: "Account Name",
    width: 200,
  },
  {
    field: "account_csn",
    headerName: "Account CSN",
    width: 100,
  },
  {
    field: "bd_person",
    headerName: "BD Person Name",
    width: 200,
  },
  {
    field: "renewal_person",
    headerName: "Renewal Person Name",
    width: 200,
  },
  {
    field: "branch",
    headerName: "Branch",
    width: 100,
  },
  {
    field: "contract_manager_email",
    headerName: "Contract Mgr. Email",
    width: 200,
  },
  {
    field: "seats",
    headerName: "Seats",
    width: 70,
  },
  {
    field: "endDate",
    headerName: "Subs End Date ",
    width: 130,
  },
  {
    field: "startDate",
    headerName: "Subs Start Date",
    width: 130,
  },
  {
    field: "trisita_status",
    headerName: "Trisita Status",
    width: 130,
  },
  {
    field: "subscriptionStatus",
    headerName: "Status",
    width: 100,
  },
  {
    field: "lastPurchaseDate",
    headerName: "Last Purchase date",
    width: 130,
  },
  {
    field: "account_group",
    headerName: "Account Group",
    width: 100,
  },
  {
    field: "subscriptionType",
    headerName: "Subscription Type",
    width: 100,
  },
  {
    field: "contract_end_date",
    headerName: "Contract EndDate",
    width: 130,
  },
  {
    field: "productLine",
    headerName: "Product Line",
    width: 250,
  },
  {
    field: "created_date",
    headerName: "Created Date",
    width: 130,
    // type: "date",
    // sortable: true,
    // filterable: true,
  },
];
