export const product_aggrement = {
  options: {
    chart: {
      height: 350,
      type: "bar",
    },
    xaxis: {
      labels: {},
      categories: [
        "MAYA",
        "PDCOLL",
        "VLTM",
        "ACDIST",
        "ACDLT",
        "3DSMAX",
        "AECCOL",
        "COLLRP",
        "CIV3D",
        "MECOLL",
        "PREMSUB",
        "RVT",
        "ADSTPR",
        "FSN",
        "SCFDM",
        "F360PMU",
        "BLD5K",
        "F360PS",
        "NAVSIM",
        "F360PMS",
        "CAMDCT",
        "SPCMKR",
        "BM36DP",
        "F36FCS",
        "ACDLTM",
        "RVTLTS",
        "INVPROSA",
        "BIMCOLL",
        "BLD550",
        "F360",
        "F360PD",
        "NAVMAN",
        "BLDUNLT",
        "A250",
        "F36MEIA",
        "PCOFFI",
        "DOCS",
        "CADMEP",
        "IWICMU",
        "INFWP",
        "QNTFY",
        "INFDU",
        "IWWSPRO",
        "F36FC",
      ],
    },
    yaxis: {
      title: {
        text: "Count",
      },
    },
    colors: ["#007BFF", "#28A745", "#FFC107"],
    plotOptions: {
      bar: {
        borderRadius: 0,
        columnWidth: "80%",
      },
    },
  },
  series: [
    {
      name: "Seats Purchased",
      data: [
        133, 1880, 348, 1953, 3643, 183, 3536, 1061, 283, 90, 27, 84, 24, 36, 1,
        5, 4, 22, 331, 34, 1, 13, 650, 1, 3, 39, 65, 12, 14, 2, 1, 4, 10004, 3,
        1, 1, 17, 2, 3, 2, 3, 2, 2, 1,
      ],
    },
    {
      name: "User Assigned",
      data: [
        104, 1695, 298, 1664, 3233, 165, 3274, 893, 274, 85, 0, 69, 24, 33, 1,
        4, 4, 20, 224, 33, 1, 1, 538, 1, 3, 23, 63, 11, 14, 2, 1, 3, 7, 3, 1, 0,
        16, 0, 1, 0, 2, 0, 0, 1,
      ],
    },
    {
      name: "Seats In Use",
      data: [
        80, 1337, 169, 1265, 2348, 119, 2784, 647, 216, 75, 0, 37, 20, 26, 1, 3,
        3, 14, 183, 28, 1, 0, 319, 0, 0, 17, 53, 6, 12, 1, 1, 2, 3, 3, 0, 0, 4,
        0, 1, 0, 0, 0, 0, 1,
      ],
    },
  ],
};
export const risk = {
  options: {
    chart: {
      type: "bar",
      height: 350,
      width: "100%",
      events: {},
    },
    xaxis: {
      categories: ["Green", "Yellow", "Red", "Unknown"],
    },
    yaxis: {
      title: {
        text: "",
      },
    },
    dataLabels: {
      position: "top",
    },
  },
  series: [
    {
      name: "contracts",
      data: [1427, 261, 542, 0],
    },
  ],
};
export const processedData = [
  {
    id: 280783,
    Account: "ORIENT BELL Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-23",
    customerCSN: 5501727888,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "1",
    seatsInUse: "0",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "8969223",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279710,
    Account: "ANGELICA DEVELOPERS Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-24",
    customerCSN: 5501729882,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "0",
    seatsInUse: "0",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "0%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "49325601",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279711,
    Account: "ANGELICA DEVELOPERS Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 5,
    subs_end_date: "2025-04-24",
    customerCSN: 5501729882,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDLT",
    productLineCode: "ACDLT",
    usersAssigned: "5",
    seatsInUse: "0",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "49325601",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280131,
    Account: "BLUE STAR Ltd",
    AccountStatus: "Active",
    branch: "Mumbai",
    contract_status: "Active",
    bd_person_name: ["Ankit Shah"],
    renewal_person_name: ["Ankit Shah"],
    seatsPurchased: 1,
    subs_end_date: "2025-04-24",
    customerCSN: 5501694036,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "1",
    seatsInUse: "0",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "15172907",
    resellerCSN: null,
    resellerName: null,
    bd_person: "Ankit Shah",
    renewal_person: "Ankit Shah",
  },
  {
    id: 280782,
    Account: "ORIENT BELL Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 2,
    subs_end_date: "2025-04-24",
    customerCSN: 5501727888,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "3DSMAX",
    productLineCode: "3DSMAX",
    usersAssigned: "1",
    seatsInUse: "0",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "50%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "8969223",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279867,
    Account: "TITAGARH WAGONS Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 5,
    subs_end_date: "2025-04-25",
    customerCSN: 5136561137,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDLT",
    productLineCode: "ACDLT",
    usersAssigned: "5",
    seatsInUse: "5",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "16601153",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279868,
    Account: "TITAGARH WAGONS Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-25",
    customerCSN: 5136561137,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "1",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "16601153",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279873,
    Account: "SURBANA JURONG INDIA PVT Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 8,
    subs_end_date: "2025-04-25",
    customerCSN: 5501731487,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "7",
    seatsInUse: "7",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "88%",
    utilisationRate: "88%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "12248228",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279932,
    Account: "HIMACHAL FUTURSTIC COMUNICATIONS LI",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 5,
    subs_end_date: "2025-04-25",
    customerCSN: 5501731167,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "4",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "80%",
    utilisationRate: "20%",
    usageRate: "25%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "49232624",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280327,
    Account: "INNOCEAN Worldwide Communication Pvt Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-25",
    customerCSN: 5501086089,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "3DSMAX",
    productLineCode: "3DSMAX",
    usersAssigned: "1",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "8118653",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280715,
    Account: "DMT CONSULTING PVT. Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 2,
    subs_end_date: "2025-04-25",
    customerCSN: 5153396739,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "CIV3D",
    productLineCode: "CIV3D",
    usersAssigned: "2",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "50%",
    usageRate: "50%",
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "49759970",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279381,
    Account: "ATMASTCO LTD-PROJECT DIVISION",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-26",
    customerCSN: 5153202241,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "PDCOLL",
    productLineCode: "PDCOLL",
    usersAssigned: "1",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "38584228",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279601,
    Account: "RECRO KARDO",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 8,
    subs_end_date: "2025-04-26",
    customerCSN: 5501087511,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDLT",
    productLineCode: "ACDLT",
    usersAssigned: null,
    seatsInUse: null,
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: null,
    utilisationRate: null,
    usageRate: null,
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "12018354",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280024,
    Account: "OEDEC ENGINEERING PVT. Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 3,
    subs_end_date: "2025-04-26",
    customerCSN: 5501700447,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDLT",
    productLineCode: "ACDLT",
    usersAssigned: "1",
    seatsInUse: "0",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "33%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "43164308",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280628,
    Account: "GKW Consult GmbH",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-26",
    customerCSN: 5127406989,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDLT",
    productLineCode: "ACDLT",
    usersAssigned: "1",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "38579160",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279804,
    Account: "CG Power and Industrial Solutions Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 5,
    subs_end_date: "2025-04-27",
    customerCSN: 5154352719,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "PDCOLL",
    productLineCode: "PDCOLL",
    usersAssigned: null,
    seatsInUse: null,
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: null,
    utilisationRate: null,
    usageRate: null,
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "38614018",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279916,
    Account: "CG Power and Industrial Solutions Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 5,
    subs_end_date: "2025-04-27",
    customerCSN: 5131210983,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "PDCOLL",
    productLineCode: "PDCOLL",
    usersAssigned: "5",
    seatsInUse: "5",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "29684616",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280119,
    Account: "CG POWER AND INDUSTRIAL SOLUTIONS Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 2,
    subs_end_date: "2025-04-27",
    customerCSN: 5156359321,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "1",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "50%",
    utilisationRate: "50%",
    usageRate: "100%",
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "48403527",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280330,
    Account: "BENGAL PEERLESS HOUSING DEV Co. Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 2,
    subs_end_date: "2025-04-27",
    customerCSN: 5103384427,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "AECCOL",
    productLineCode: "AECCOL",
    usersAssigned: "2",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "50%",
    usageRate: "50%",
    riskCategory: "Yellow",
    engagementCategory: "Medium Engaged Customers",
    premiumFlag: false,
    tenantId: "27487209",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280521,
    Account: "CG POWER AND INDUSTRIAL SOLUTIONS L",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-27",
    customerCSN: 5150770532,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "1",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "7646477",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279756,
    Account: "Brij Gopal Construction Co. Pvt. Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-28",
    customerCSN: 5155701003,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDLT",
    productLineCode: "ACDLT",
    usersAssigned: "1",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "49295769",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280287,
    Account: "SGP INDUSTRIAL",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-28",
    customerCSN: 5501735256,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "AECCOL",
    productLineCode: "AECCOL",
    usersAssigned: "1",
    seatsInUse: "0",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "0%",
    usageRate: "0%",
    riskCategory: "Red",
    engagementCategory: "Low Engaged Customers",
    premiumFlag: false,
    tenantId: "49310396",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279500,
    Account: "LLOYD INSULATIONS (INDIA) Ltd",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 1,
    subs_end_date: "2025-04-29",
    customerCSN: 5501735977,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "ACDIST",
    productLineCode: "ACDIST",
    usersAssigned: "1",
    seatsInUse: "1",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "49301159",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 279801,
    Account: "FERVENT COMMUNICATION PRIVATE Ltd",
    AccountStatus: "Active",
    branch: "Delhi",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 2,
    subs_end_date: "2025-04-29",
    customerCSN: 5501736378,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "3DSMAX",
    productLineCode: "3DSMAX",
    usersAssigned: "2",
    seatsInUse: "2",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "49331008",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
  {
    id: 280233,
    Account: "Indian Oil Corp.",
    AccountStatus: "Active",
    branch: "Kolkata",
    contract_status: "Active",
    bd_person_name: [],
    renewal_person_name: [],
    seatsPurchased: 2,
    subs_end_date: "2025-04-29",
    customerCSN: 5141004577,
    partnerCSN: 5102086717,
    ownerType: "ACCOUNT",
    offeringCode: "AECCOL",
    productLineCode: "AECCOL",
    usersAssigned: "2",
    seatsInUse: "2",
    usersAssignedProRated: null,
    seatsInUseProRated: null,
    assignmentRate: "100%",
    utilisationRate: "100%",
    usageRate: "100%",
    riskCategory: "Green",
    engagementCategory: "High Engaged Customers",
    premiumFlag: false,
    tenantId: "15820398",
    resellerCSN: null,
    resellerName: null,
    bd_person: "",
    renewal_person: "",
  },
];
export const columns = [
  {
    field: "id",
    headerName: "Serial No.",
    width: 120,
  },
  {
    field: "customerCSN",
    headerName: "customerCSN",
    width: 150,
  },
  {
    field: "bd_person",
    headerName: "BD Person Name",
    width: 200,
  },
  {
    field: "renewal_person",
    headerName: "Renewal Person Name",
    width: 200,
  },
  {
    field: "Account",
    headerName: "Account",
    width: 200,
  },
  {
    field: "AccountStatus",
    headerName: "Autodesk Account Status",
    width: 120,
  },
  {
    field: "contract_status",
    headerName: "Trisita Account Status",
    width: 120,
  },
  {
    field: "subs_end_date",
    headerName: "Subs End Date",
    width: 120,
  },
  {
    field: "branch",
    headerName: "Branch",
    width: 100,
  },
  {
    field: "productLineCode",
    headerName: "productLineCode",
    width: 200,
  },
  {
    field: "seatsPurchased",
    headerName: "seatsPurchased",
    width: 200,
  },
  {
    field: "usersAssigned",
    headerName: "usersAssigned",
    width: 200,
  },
  {
    field: "seatsInUse",
    headerName: "seatsInUse",
    width: 200,
  },
  {
    field: "assignmentRate",
    headerName: "assignmentRate",
    width: 200,
  },
  {
    field: "utilisationRate",
    headerName: "utilisationRate",
    width: 200,
  },
  {
    field: "usageRate",
    headerName: "usageRate",
    width: 200,
  },
  {
    field: "riskCategory",
    headerName: "riskCategory",
    width: 200,
  },
  {
    field: "engagementCategory",
    headerName: "engagementCategory",
    width: 200,
  },
  {
    field: "tenantId",
    headerName: "tenantId",
    width: 200,
  },
];
