export const accountData = [
  {
    id: 6874,
    csn: 5501593303,
    email: "info@1architecturalconsultants.com",
    phone: null,
    name: "1 Architectural Consultants",
    industryGroup: "AEC",
    industrySegment: "Architecture Services",
    industrySubSegment: "Architecture",
    address1: "Civic Centre, M.M.G.S Marg,",
    city: "Mumbai",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Mumbai",
    branch_object: null,
    user_assign: ["Rahul Chheda"],
    renewal_person: ["Rahul Chheda"],
  },
  {
    id: 5858,
    csn: 5501281536,
    email: null,
    phone: null,
    name: "2M RESEARCH PRIVATE Ltd",
    industryGroup: "Unknown",
    industrySegment: "Unknown",
    industrySubSegment: "Unknown",
    address1: "MIDC, Butibori Industrial area,",
    city: "Nagpur",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6850,
    csn: 5502185195,
    email: null,
    phone: null,
    name: "2M RESEARCH PVT. Ltd",
    industryGroup: "Unknown",
    industrySegment: "Unknown",
    industrySubSegment: "Unknown",
    address1: "16 Premises",
    city: "New Town",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 5477,
    csn: 5106985515,
    email: null,
    phone: null,
    name: "2 Tettra School",
    industryGroup: "OTH",
    industrySegment: "Other",
    industrySubSegment: "Other",
    address1: "Air Force Station, C/O 99 APO",
    city: "Bagdogra",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: "Mumbai",
    branch_object: null,
    user_assign: ["Ankit Shah", "Kamran Ahmed"],
    renewal_person: ["Kamran Ahmed"],
  },
  {
    id: 4159,
    csn: 5107121028,
    email: null,
    phone: null,
    name: "3ds Architect",
    industryGroup: "Unknown",
    industrySegment: "Unknown",
    industrySubSegment: "Unknown",
    address1: "97 Kharavel Nagar",
    city: "Bhubanneswar",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6115,
    csn: 5106740834,
    email: "3guys32a@gmail.com",
    phone: "+913324752184",
    name: "3 Guys",
    industryGroup: "AEC",
    industrySegment: "Buildings",
    industrySubSegment: "Retail & Wholesale",
    address1: "32A Elgin Rd",
    city: "Kolkata",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 4274,
    csn: 5104091953,
    email: "rajatdalui@yahoo.com",
    phone: "+9.19832E+11",
    name: "4TH DIMENSION",
    industryGroup: "AEC",
    industrySegment: "Buildings",
    industrySubSegment: "Retail & Wholesale",
    address1: "1/22 P G M S Rd",
    city: "Kolkata",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 4084,
    csn: 5153000319,
    email: "amit@99watts.co.in",
    phone: null,
    name: "99 Watts Energy Solutions Pvt. Ltd",
    industryGroup: "Unknown",
    industrySegment: "Unknown",
    industrySubSegment: "Unknown",
    address1: "503 Mon Repos Chs 75 Demonte Park",
    city: "Bandra West,Mumbai",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6255,
    csn: 5114508998,
    email: "a1_jumboxerox@yahoo.co.in",
    phone: "+919122254496",
    name: "A1 Jumbo Xerox",
    industryGroup: "OTH",
    industrySegment: "Other",
    industrySubSegment: "Other Services",
    address1: "B/2 Poornima Bldg Dada Patil",
    city: "Thane",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6163,
    csn: 5122596593,
    email: null,
    phone: null,
    name: "A2G CIVIL ENGINEERING SERVICES PVT. LTD",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "B-401 Dipti Classic Suren Rd",
    city: "Mumbai",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 4013,
    csn: 5100805535,
    email: null,
    phone: null,
    name: "A4 Creation Pty Ltd",
    industryGroup: "OTH",
    industrySegment: "Other",
    industrySubSegment: "Other Services",
    address1: "88/B Lake View Rd",
    city: "Kolkata",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 3021,
    csn: 5138960616,
    email: null,
    phone: null,
    name: "AABSYS INFORMATION TECHNOLOGY PVT",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "54 & E 54 - 1 Ltd Plot No E",
    city: "Bhubaneswar",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6181,
    csn: 5151235656,
    email: "info@aabsys.com",
    phone: "+919167466210",
    name: "AABSYS INFORMATION TECHNOLOGY PVT. Ltd",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "E/54 Nad E/54/1",
    city: "Bhubaneswar",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 5361,
    csn: 5109908502,
    email: "admin@aabsys.com",
    phone: "+919338463455",
    name: "AABSYSINFORMATIONTECHNOLOGYPVTLTD",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "Plot No E/54 & E/54-1 Infocity",
    city: "Bhubaneswar",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 5470,
    csn: 5123161029,
    email: "shyam.mohapatra@aabsys.com",
    phone: "+6746621016",
    name: "AABSYS INFO TECH PVT. Ltd",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "& E/54/1 Plot No E/54",
    city: "Bhubaneswar",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6975,
    csn: 5502315575,
    email: "admin@aadhyaanimatics.com",
    phone: null,
    name: "AADHYA ANIMATICS PVT Ltd",
    industryGroup: "Unknown",
    industrySegment: "Unknown",
    industrySubSegment: "Unknown",
    address1: "175 & 176 91 14th Cross Road",
    city: "Bengaluru",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6337,
    csn: 5501755245,
    email: "aadityainnovations@gmail.com",
    phone: "+918080129755",
    name: "AADITYA INNOVATIONS PVT. Ltd",
    industryGroup: "MFG",
    industrySegment: "Process Manufacturing",
    industrySubSegment: "Metal & Ore Processing",
    address1: "RTC – 43, RABALE",
    city: "Navi Mumbai",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Mumbai",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 3009,
    csn: 5125174500,
    email: "ptan1@rediffmail.com",
    phone: "+919415307079",
    name: "AAKAAR",
    industryGroup: "AEC",
    industrySegment: "Architecture Services",
    industrySubSegment: "Architecture",
    address1: "Sachcha Vihar Colony",
    city: "Allahabad",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6171,
    csn: 5501676962,
    email: "project@aakaararchitects.com",
    phone: null,
    name: "AAKAAR ARCHITECTS",
    industryGroup: "AEC",
    industrySegment: "Architecture Services",
    industrySubSegment: "Architecture",
    address1: "N-2/14, IRC Village , Nayapalli",
    city: "Bhubaneswar",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 5125,
    csn: 5108569378,
    email: null,
    phone: null,
    name: "AAKAR",
    industryGroup: "MFG",
    industrySegment: "Other Manufacturing",
    industrySubSegment: "Textiles & Leather",
    address1: "166 5d Merlin Links",
    city: "Kolkata",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6766,
    csn: 5156470531,
    email: null,
    phone: null,
    name: "Aakar Architects",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "N-2/14",
    city: "Bhubaneswar",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 5371,
    csn: 5106234484,
    email: "silarch@yahoo.com",
    phone: "+916746532798",
    name: "AAKAR ARCHITECTS",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "B-16 Indradhanu Market Complex",
    city: "Bhubaneswar",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 3170,
    csn: 5117627806,
    email: "accounts@aakararchitect.org",
    phone: "+919133225225",
    name: "Aakar Architects & Consultants",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "Commercial Centre",
    city: "Mumbai",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 6304,
    csn: 5117627806,
    email: "aakararchitect@gmail.com",
    phone: "+919122261334",
    name: "Aakar Architects & Consultants",
    industryGroup: "AEC",
    industrySegment: "Engineering Service Providers",
    industrySubSegment: "Engineering Services",
    address1: "Commercial Centre",
    city: "Mumbai",
    status: "Active",
    contract_status: "Expired",
    buyingReadinessScore: null,
    branch: null,
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
  {
    id: 5759,
    csn: 5151471264,
    email: null,
    phone: null,
    name: "AAKASH INDIA PROJECTS AND BUILDERS",
    industryGroup: "AEC",
    industrySegment: "Buildings",
    industrySubSegment: "Retail & Wholesale",
    address1: "Payal Cinema Complex Mango",
    city: "Jamshedpur",
    status: "Active",
    contract_status: "Active",
    buyingReadinessScore: null,
    branch: "Kolkata",
    branch_object: null,
    user_assign: [" "],
    renewal_person: [" "],
  },
];
export const columns = [
  {
    field: "csn",
    headerName: "CSN",
    width: 150,
  },
  {
    field: "user_assign",
    headerName: "BD Person Name",
    width: 160,
  },
  {
    field: "name",
    headerName: "Account Name",
    width: 160,
  },
  {
    field: "industryGroup",
    headerName: "Industry",
    width: 100,
  },
  {
    field: "industrySegment",
    headerName: "Segment",
    width: 160,
  },
  {
    field: "industrySubSegment",
    headerName: "Sub Segment",
    width: 160,
  },
  {
    field: "address1",
    headerName: "Address",
    width: 160,
  },
  {
    field: "city",
    headerName: "City",
    width: 150,
  },
  {
    field: "email",
    headerName: "Email",
    width: 150,
  },
  {
    field: "phone",
    headerName: "Contact No",
    width: 150,
  },
  {
    field: "status",
    headerName: "Autodesk Account Status",
    width: 120,
  },
  {
    field: "contract_status",
    headerName: "Trisita Account Status",
    width: 120,
  },
  {
    field: "buyingReadinessScore",
    headerName: "Rediness Score",
    width: 130,
  },
  {
    field: "renewal_person",
    headerName: "Renewal Person Name",
    width: 160,
  },
  {
    field: "branch",
    headerName: "Branch",
    width: 100,
  },
  {
    field: "",
    headerName: "Action",
    width: 150,
  },
];
export const LineChartData = {
  series: [
    {
      name: "Accounts",
      data: [1801, 481, 432, 1199, 106, 144],
    },
  ],
  options: {
    chart: {
      type: "line",
      width: "100%",
      zoom: {
        enabled: false,
      },
      height: 350,
    },
    dataLabels: {
      enabled: false,
    },
    stroke: {
      curve: "straight",
    },
    title: {
      text: "",
      align: "left",
    },
    grid: {
      row: {
        colors: ["#f3f3f3", "transparent"],
        opacity: 0.5,
      },
    },
    xaxis: {
      categories: ["AEC", "Unknown", "OTH", "MFG", "EDU", "M&E"],
    },
  },
};
export const ChartData = {
  series: [10, 20, 30, 40, 50],
  options: {
    chart: {
      type: "donut",
      events: {},
      height: 350,
      width: "100%",
      stacked: true,
    },
    colors: ["#5372b9", "#90be82", "#fdc66d", "#fa7870", "#6eb8d8"],
    labels: ["25", "50", "75", "100", "NA"],
    legend: {
      show: true,
      position: "right",
    },
    dataLabels: {
      enabled: true,
      offsetY: -20,
    },
    responsive: [
      {
        breakpoint: 480,
        options: {
          chart: {
            width: 200,
          },
          legend: {
            position: "bottom",
          },
        },
      },
    ],
  },
};
export const barChartData = {
  series: [],
  options: {
    colors: ["#5372b9", "#90be82", "#9C27B0"],
    chart: {
      events: {},
      type: "bar",
      width: "100%",
      stacked: true,
      height: 350,
      toolbar: {
        show: true,
      },
      zoom: {
        enabled: true,
      },
    },
    responsive: [
      {
        breakpoint: 480,
        options: {
          legend: {
            position: "bottom",
            offsetX: -10,
            offsetY: 0,
          },
        },
      },
    ],
    plotOptions: {
      bar: {
        horizontal: false,
        borderRadius: 1,
        dataLabels: {
          total: {
            enabled: true,
            style: {
              fontSize: "13px",
              fontWeight: 900,
            },
          },
        },
      },
    },
    xaxis: {
      categories: [
        "Kolkata",
        "Mumbai",
        "Bhubaneswar",
        "Navi mumbai",
        "New delhi",
        "Guwahati",
        "Thane",
        "Pune",
        "Gurgaon",
        "Howrah",
        "Jamshedpur",
        "Ranchi",
      ],
    },
    legend: {
      position: "right",
      offsetY: 40,
    },
    fill: {
      opacity: 1,
    },
  },
};
