export const options = {
  chart: {
    events: {},
    type: "bar",
    height: 350,
    width: "100%",
  },
  xaxis: {
    categories: [
      "ACDLT",
      "ACDIST",
      "AECCOL",
      "PDCOLL",
      "ACD",
      "COLLRP",
      "CIV3D",
      "RVTLTS",
      "3DSMAX",
      "AMECH_PP",
      "BDSPRM",
      "ARCHDESK",
      "MAP",
      "RVT",
      "MAYA",
      "INVLTS",
      "PDSP",
      "REVITS",
      "ADSTPR",
      "VLTM",
      "PDSU",
      "PDSS",
      "F360PMS",
      "INVPROSA",
      "IDSP",
      "ARNOL",
      "NAVSIM",
      "MECOLL",
      "DSSTD",
      "FSN",
      "ACAD_E",
      "F360PS",
      "DSPRM",
      "ACDLTM",
      "INVLT",
      "REVSU",
      "NAVMAN",
      "CONCRD",
      "BM36DP",
      "IDSU",
      "ARDES",
      "BLDSYS",
      "CADMEP",
      "BDSADV",
      "ASPACD",
      "PREMSUB",
      "ENCSU",
      "BDSS",
      "BLD550",
      "IDSS",
    ],
  },
  yaxis: {
    title: {
      text: "",
    },
  },
  dataLabels: {
    position: "top",
  },
};

export const series = [
  {
    name: "seats",
    data: [
      5444, 2632, 4128, 2114, 1022, 1139, 596, 473, 323, 562, 635, 298, 341,
      121, 230, 184, 109, 237, 89, 363, 113, 74, 40, 82, 93, 595, 520, 105, 79,
      37, 25, 24, 24, 25, 19, 36, 28, 39, 660, 18, 11, 36, 17, 20, 15, 47, 22,
      21, 16, 10,
    ],
  },
];

export const accountGroupChartData = {
  options: {
    labels: [
      "Territory",
      "Emerging Strategic Account",
      "Strategic Territory Emerging",
      "null",
      "Midmarket Federal",
    ],
    chart: {
      type: "pie",
      height: 350,
    },
    legend: {
      position: "bottom",
    },
  },
  series: [3952, 1573, 438, 18, 1],
};

export const amountPerMOnth = {
  options: {
    chart: {
      height: 350,
      type: "bar",
    },
    xaxis: {
      categories: [
        "2025-05",
        "2025-06",
        "2025-07",
        "2025-08",
        "2025-09",
        "2025-10",
        "2025-11",
        "2025-12",
        "2026-01",
        "2026-02",
        "2026-03",
        "2026-04",
      ],
      title: {
        text: "Months",
      },
    },
    yaxis: {
      title: {
        text: "Price",
      },
    },
    colors: ["#007BFF", "#FF5733"],
    plotOptions: {
      bar: {
        borderRadius: 5,
        columnWidth: "50%",
      },
    },
  },
  series: [
    {
      name: "DTP Price",
      data: [
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
      ],
    },
    {
      name: "ACV Price",
      data: [
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
        "0.00",
      ],
    },
  ],
};

export const riskRetentionShows = {
  series: [812, 2111, 790, 198, 24, 2047],
  options: {
    chart: {
      width: 350,
      height: 350,
      type: "pie",
    },
    labels: ["Very High", "High", "Medium", "Low", "Very Low", "Undefined"],
    legend: {
      position: "top",
      horizontalAlign: "center",
    },
  },
};

export const accountTypeChartData = {
  options: {
    labels: [
      "Government",
      "End Customer",
      "A.D.N.",
      "Training Center",
      "Strategic Account",
      "Reseller",
    ],
    chart: {
      type: "pie",
      height: 350,
    },
    legend: {
      position: "bottom",
    },
  },
  series: [381, 5590, 1, 2, 2, 6],
};

export const onBoardHealth = {
  options: {
    chart: {
      events: {},
      type: "bar",
      height: 350,
      width: "100%",
    },
    xaxis: {
      categories: [
        "Very High",
        "High",
        "Medium",
        "Low",
        "Very Low",
        "Undefined",
      ],
    },
    yaxis: {
      title: {
        text: "",
      },
    },
    dataLabels: {
      position: "top",
    },
  },
  series: [
    {
      name: "Subscription",
      data: [812, 2111, 790, 198, 24, 2047],
    },
  ],
};

export const processedData = [
  {
    id: 964518,
    account_id: 3884,
    subscriptionReferenceNumber: "390-25153629",
    account_name: "Khardha Municipality",
    account_csn: 5102410656,
    part_number: null,
    branch: null,
    startDate: "2007-04-16",
    endDate: "2008-04-15",
    subscriptionType: "Renewable Maintenance",
    groupName: "khardha Municipality",
    contract_manager_email: "khardahmunicipality@yahoo.co.in",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-04-16",
    contract_end_date: "2008-04-15",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "Government",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 961680,
    account_id: 3742,
    subscriptionReferenceNumber: "390-25167386",
    account_name: "KHADIM INDIA Ltd",
    account_csn: 5102452434,
    part_number: null,
    branch: null,
    startDate: "2007-05-04",
    endDate: "2008-05-03",
    subscriptionType: "Renewable Maintenance",
    groupName: "KHADIM INDIA LTD",
    contract_manager_email: "kali.majumder@khadims.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-05-04",
    contract_end_date: "2008-05-03",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 962125,
    account_id: 4339,
    subscriptionReferenceNumber: "390-25168871",
    account_name: "CANAM KOLKATA Inc.",
    account_csn: 5101166228,
    part_number: null,
    branch: "Kolkata",
    startDate: "2007-05-08",
    endDate: "2008-05-07",
    subscriptionType: "Renewable Maintenance",
    groupName: "STEEL PLUS LIMITED",
    contract_manager_email: "jayatpai.de@canam.ws",
    seats: 2,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-05-08",
    contract_end_date: "2008-05-07",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 963270,
    account_id: 2929,
    subscriptionReferenceNumber: "390-42793672",
    account_name: "BENGAL AMBUJA HOUSING DEV Ltd",
    account_csn: 5101587759,
    part_number: null,
    branch: null,
    startDate: "2007-06-15",
    endDate: "2008-06-13",
    subscriptionType: "Renewable Maintenance",
    groupName: "RAS-5ST-NW",
    contract_manager_email: "cpaul@ambujarealty.com",
    seats: 5,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-26",
    contract_start_date: "2007-06-14",
    contract_end_date: "2008-06-13",
    productLine: "Autodesk AutoCAD Revit Architecture Suite",
    productLineCode: "REVITS",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 961474,
    account_id: 6179,
    subscriptionReferenceNumber: "390-34390997",
    account_name: "TATA SPONGE IRON Ltd",
    account_csn: 5108217224,
    part_number: null,
    branch: null,
    startDate: "2007-07-02",
    endDate: "2008-07-01",
    subscriptionType: "Renewable Maintenance",
    groupName: "TATA SPONGE IRON LTD",
    contract_manager_email: "sjena@tatasponge.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-18",
    contract_start_date: "2007-07-02",
    contract_end_date: "2008-07-01",
    productLine: "AutoCAD Map 3D",
    productLineCode: "MAP",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 964792,
    account_id: 5117,
    subscriptionReferenceNumber: "390-34390898",
    account_name: "Cadopia India Pvt. Ltd",
    account_csn: 5102574518,
    part_number: null,
    branch: null,
    startDate: "2007-07-02",
    endDate: "2008-07-01",
    subscriptionType: "Renewable Maintenance",
    groupName: "CADOPIA (INDIA) PRIVATE LIMITED",
    contract_manager_email: "suryas@cadopia.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-18",
    contract_start_date: "2007-07-02",
    contract_end_date: "2008-07-01",
    productLine: "AutoCAD Map 3D",
    productLineCode: "MAP",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 964119,
    account_id: 4747,
    subscriptionReferenceNumber: "390-25226279",
    account_name: "ITC Ltd",
    account_csn: 5139969466,
    part_number: null,
    branch: "Kolkata",
    startDate: "2007-07-10",
    endDate: "2008-07-09",
    subscriptionType: "Renewable Maintenance",
    groupName: "ITC LIMITED (ITD)",
    contract_manager_email: "raja.mukherjee@itc.in",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-07-10",
    contract_end_date: "2008-07-09",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 964493,
    account_id: 6141,
    subscriptionReferenceNumber: "390-42529891",
    account_name: "Public Health Engineering",
    account_csn: 5102595910,
    part_number: null,
    branch: null,
    startDate: "2007-07-11",
    endDate: "2008-07-10",
    subscriptionType: "Renewable Maintenance",
    groupName: "Public Health Engineering",
    contract_manager_email: "phed_kolkata@yahoo.co.in",
    seats: 6,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-26",
    contract_start_date: "2007-07-11",
    contract_end_date: "2008-07-10",
    productLine: "Civil 3D",
    productLineCode: "CIV3D",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "Government",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 964630,
    account_id: 3374,
    subscriptionReferenceNumber: "390-28387588",
    account_name: "EZEESOFT",
    account_csn: 5101934909,
    part_number: null,
    branch: null,
    startDate: "2006-07-28",
    endDate: "2008-07-27",
    subscriptionType: "Renewable Maintenance",
    groupName: "MAX_SA",
    contract_manager_email: "avinash.chandiramani@gmail.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-11",
    contract_start_date: "2007-07-28",
    contract_end_date: "2008-07-27",
    productLine: "Autodesk 3ds Max",
    productLineCode: "3DSMAX",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 964086,
    account_id: 3181,
    subscriptionReferenceNumber: "390-34393571",
    account_name: "GEOLOGICAL SURVEY OF INDIA",
    account_csn: 5102641031,
    part_number: null,
    branch: null,
    startDate: "2007-08-01",
    endDate: "2008-07-31",
    subscriptionType: "Renewable Maintenance",
    groupName: "Geological Survey Of India,",
    contract_manager_email: "gsi.ero@vsnl.com",
    seats: 5,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-18",
    contract_start_date: "2007-08-01",
    contract_end_date: "2008-07-31",
    productLine: "AutoCAD Map 3D",
    productLineCode: "MAP",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "Government",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 963336,
    account_id: 3918,
    subscriptionReferenceNumber: "390-28446481",
    account_name: "NAHAR MANISH",
    account_csn: 5131752861,
    part_number: null,
    branch: null,
    startDate: "2007-08-21",
    endDate: "2008-08-19",
    subscriptionType: "Renewable Maintenance",
    groupName: "MAX_SA",
    contract_manager_email: "nahardecor@yahoo.co.in",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-11",
    contract_start_date: "2007-08-20",
    contract_end_date: "2008-08-19",
    productLine: "3ds Max",
    productLineCode: "3DSMAX",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 961835,
    account_id: 5518,
    subscriptionReferenceNumber: "390-28446679",
    account_name: "T SARKAR PRODUCTION",
    account_csn: 5102677219,
    part_number: null,
    branch: null,
    startDate: "2007-08-21",
    endDate: "2008-08-19",
    subscriptionType: "Renewable Maintenance",
    groupName: "MAX_SA",
    contract_manager_email: "sarkar_tk06@rediffmail.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-11",
    contract_start_date: "2007-08-20",
    contract_end_date: "2008-08-19",
    productLine: "Autodesk 3ds Max",
    productLineCode: "3DSMAX",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 962856,
    account_id: 4339,
    subscriptionReferenceNumber: "390-19028573",
    account_name: "CANAM KOLKATA Inc.",
    account_csn: 5101166228,
    part_number: null,
    branch: "Kolkata",
    startDate: "2007-08-27",
    endDate: "2008-08-26",
    subscriptionType: "Renewable Maintenance",
    groupName: "Steel Plus Limited.",
    contract_manager_email: "jayatpal.de@canamgroupinc.com",
    seats: 5,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-05",
    contract_start_date: "2007-08-27",
    contract_end_date: "2008-08-26",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 962261,
    account_id: 5256,
    subscriptionReferenceNumber: "390-19033820",
    account_name: "Siemens VAI Metals Technologies Pvt. Ltd",
    account_csn: 5108115635,
    part_number: null,
    branch: null,
    startDate: "2007-09-03",
    endDate: "2008-09-02",
    subscriptionType: "Renewable Maintenance",
    groupName: "VAI Engineering & Automation",
    contract_manager_email: "ghosh.partha@siemens.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-05",
    contract_start_date: "2007-09-03",
    contract_end_date: "2008-09-02",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 961289,
    account_id: 4653,
    subscriptionReferenceNumber: "390-19034612",
    account_name: "SUR INDUSTRIES PVT. Ltd",
    account_csn: 5102709439,
    part_number: null,
    branch: null,
    startDate: "2007-09-03",
    endDate: "2008-09-02",
    subscriptionType: "Renewable Maintenance",
    groupName: "Sur Industries Pvt. Ltd",
    contract_manager_email: "surind@vsnl.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-05",
    contract_start_date: "2007-09-03",
    contract_end_date: "2008-09-02",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 959939,
    account_id: 3260,
    subscriptionReferenceNumber: "390-25272997",
    account_name: "ROURKELA STEEL PLANT",
    account_csn: 5102708952,
    part_number: null,
    branch: null,
    startDate: "2007-09-03",
    endDate: "2008-09-02",
    subscriptionType: "Renewable Maintenance",
    groupName: "ROURKELA STEEL PLANT",
    contract_manager_email: "s.tripathy@sailrsp.co.in",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-09-03",
    contract_end_date: "2008-09-02",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "Government",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 964432,
    account_id: 4240,
    subscriptionReferenceNumber: "390-25273987",
    account_name: "ULUBERIA MUNICIPALITY",
    account_csn: 5102711289,
    part_number: null,
    branch: null,
    startDate: "2007-09-04",
    endDate: "2008-09-03",
    subscriptionType: "Renewable Maintenance",
    groupName: "ULUBERIA MUNICIPALITY",
    contract_manager_email: "uluberia.municipality@gmail.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-09-04",
    contract_end_date: "2008-09-03",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 959928,
    account_id: 6040,
    subscriptionReferenceNumber: "390-25312886",
    account_name: "HINDUSTHAN NATIONAL GLASS & IND LTD",
    account_csn: 5102731127,
    part_number: null,
    branch: null,
    startDate: "2007-09-16",
    endDate: "2008-09-15",
    subscriptionType: "Renewable Maintenance",
    groupName: "ACAD-SA-2",
    contract_manager_email: "bpandey@hngil.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-09-16",
    contract_end_date: "2008-09-15",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 961377,
    account_id: 6040,
    subscriptionReferenceNumber: "390-25312985",
    account_name: "HINDUSTHAN NATIONAL GLASS & IND LTD",
    account_csn: 5102731127,
    part_number: null,
    branch: null,
    startDate: "2007-09-16",
    endDate: "2008-09-15",
    subscriptionType: "Renewable Maintenance",
    groupName: "ACAD_SA-1",
    contract_manager_email: "bpandey@hngil.com",
    seats: 2,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-09-16",
    contract_end_date: "2008-09-15",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 963903,
    account_id: 4747,
    subscriptionReferenceNumber: "390-25323576",
    account_name: "ITC Ltd",
    account_csn: 5139969466,
    part_number: null,
    branch: "Kolkata",
    startDate: "2007-09-17",
    endDate: "2008-09-16",
    subscriptionType: "Renewable Maintenance",
    groupName: "ITC LIMITED (ITD)",
    contract_manager_email: "raja.mukherjee@itc.in",
    seats: 4,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-09-17",
    contract_end_date: "2008-09-16",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 963643,
    account_id: 6143,
    subscriptionReferenceNumber: "390-25292595",
    account_name: "Pamach Engineering Pvt. Ltd",
    account_csn: 5102761429,
    part_number: null,
    branch: null,
    startDate: "2007-09-25",
    endDate: "2008-09-24",
    subscriptionType: "Renewable Maintenance",
    groupName: "PAMACH Engineering Pvt. Ltd.",
    contract_manager_email: "rvsingh@pamach.co.in",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-09-25",
    contract_end_date: "2008-09-24",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 964534,
    account_id: 4186,
    subscriptionReferenceNumber: "390-25294377",
    account_name: "RAJARHAT GOPALPUR MUNICIPALITY.",
    account_csn: 5102765355,
    part_number: null,
    branch: null,
    startDate: "2007-09-26",
    endDate: "2008-09-25",
    subscriptionType: "Renewable Maintenance",
    groupName: "RAJARHAT GOPALPUR MUNICIPALITY",
    contract_manager_email: "chairmanrgm@gmail.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-09-26",
    contract_end_date: "2008-09-25",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "Government",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 961061,
    account_id: 4339,
    subscriptionReferenceNumber: "390-19052824",
    account_name: "CANAM KOLKATA Inc.",
    account_csn: 5101166228,
    part_number: null,
    branch: "Kolkata",
    startDate: "2007-09-28",
    endDate: "2008-09-27",
    subscriptionType: "Renewable Maintenance",
    groupName: "Steel Plus Limited.",
    contract_manager_email: "jayatpal.de@canamgroupinc.com",
    seats: 6,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-05",
    contract_start_date: "2007-09-28",
    contract_end_date: "2008-09-27",
    productLine: "AutoCAD LT",
    productLineCode: "ACDLT",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 961119,
    account_id: 6232,
    subscriptionReferenceNumber: "390-25297941",
    account_name: "RAJ AGRAWAL & ASSOCIATES",
    account_csn: 5102466492,
    part_number: null,
    branch: null,
    startDate: "2007-10-02",
    endDate: "2008-09-30",
    subscriptionType: "Renewable Maintenance",
    groupName: "PTD-A-SA",
    contract_manager_email: null,
    seats: 5,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-08",
    contract_start_date: "2007-10-01",
    contract_end_date: "2008-09-30",
    productLine: "AutoCAD",
    productLineCode: "ACD",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Territory",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "End Customer",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
  {
    id: 963210,
    account_id: 3985,
    subscriptionReferenceNumber: "390-34397531",
    account_name: "BUDGE BUDGE MUNICIPALITY",
    account_csn: 5102804090,
    part_number: null,
    branch: null,
    startDate: "2007-10-10",
    endDate: "2008-10-09",
    subscriptionType: "Renewable Maintenance",
    groupName: "Budge Budge Municipality",
    contract_manager_email: "biswas.tapas@gmail.com",
    seats: 1,
    subscriptionStatus: "Expired",
    lastPurchaseDate: "2008-03-18",
    contract_start_date: "2007-10-10",
    contract_end_date: "2008-10-09",
    productLine: "AutoCAD Map 3D",
    productLineCode: "MAP",
    retention_health_riskBand: null,
    bd_person_first_names: [],
    renewal_person_first_names: [],
    trisita_status: "Expired",
    programType: null,
    account_group: "Emerging Strategic Account",
    contract_term: null,
    switchType: null,
    switchYear: null,
    third_party_names: [],
    dtp_price: 0,
    acv_price: 0,
    account_type: "Government",
    bd_person: "",
    renewal_person: "",
    third_party: "",
  },
];
